### ISSUE TITLE
Vonfry 倉庫需要更新鏈接

### ISSUE THREAD

**Issue by jackyliu16** [nixos-cn/NixOS-CN-telegram#21]
今天早上在嘗試打開鏈接進行檢索的時候，發現該超鏈接指向的倉庫404了

**Comment by Vonfry** [comment]
ping @LEXUGE

**Comment by LEXUGE** [comment]
看起来并没有？
旧的仓库archive了
新的仓库 https://github.com/LEXUGE/flake/

**Comment by jackyliu16** [comment]
sorry, 剛想改成Vonfry
https://gitlab.com/Vonfry/dotfiles/-/tree/develop/etc/nixos
Harry Ying 是我下一個要看的倉庫，然後誤操作複製上去了
